### PR TITLE
BREAKING: Drop Python 2.7 and 3.0-3.6 support, unbreak 3.10

### LINKED ISSUE #127: Current seesaw-kit is not compatible with Python 3.10.x
As requested by @Arkiver2  

### Cause:
Seems like `MutableMapping` got removed in Python 3.10 (https://docs.python.org/3/library/collections.html) though I can not find a changelog entry for it in the official docs... 
It still exists in module `collections.abc`

```
Traceback (most recent call last):
  File "/mnt/seesaw-kit/./run-pipeline3", line 4, in <module>
    from seesaw.script.run_pipeline import main
  File "/mnt/seesaw-kit/seesaw/script/run_pipeline.py", line 11, in <module>
    from seesaw.runner import SimpleRunner
  File "/mnt/seesaw-kit/seesaw/runner.py", line 11, in <module>
    from seesaw.item import Item
  File "/mnt/seesaw-kit/seesaw/item.py", line 13, in <module>
    class ItemData(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
```

### Reproduce:
```
git clone https://github.com/ArchiveTeam/seesaw-kit.git
λ docker run --rm --name alpine-testing -v $(pwd):/mnt/seesaw-kit -it --entrypoint=/bin/ash python:3-alpine

/ # python --version
Python 3.10.1

/ # cd /mnt/seesaw-kit/ && ls -alh
total 184K   
drwxrwxr-x    7 1000     1000        4.0K Jan 10 10:00 .
drwxr-xr-x    1 root     root        4.0K Jan 10 10:16 ..
drwxrwxr-x    6 1000     1000        4.0K Jan 10 10:00 .git
-rw-rw-r--    1 1000     1000         132 Jan 10 10:00 .gitignore
-rw-rw-r--    1 1000     1000         392 Jan 10 10:00 .travis.yml
-rw-rw-r--    1 1000     1000        1.9K Jan 10 10:00 LICENSE.txt
-rw-rw-r--    1 1000     1000         346 Jan 10 10:00 MANIFEST.in
-rw-rw-r--    1 1000     1000        2.5K Jan 10 10:00 README.md
drwxrwxr-x    3 1000     1000        4.0K Jan 10 10:00 doc
drwxrwxr-x    2 1000     1000        4.0K Jan 10 10:00 examples
-rw-rw-r--    1 1000     1000          43 Jan 10 10:00 requirements.txt
-rwxrwxr-x    1 1000     1000         106 Jan 10 10:00 run-pipeline
-rwxrwxr-x    1 1000     1000         280 Jan 10 10:00 run-pipeline2
-rwxrwxr-x    1 1000     1000         280 Jan 10 10:00 run-pipeline3
-rwxrwxr-x    1 1000     1000         105 Jan 10 10:00 run-warrior
-rwxrwxr-x    1 1000     1000         279 Jan 10 10:00 run-warrior2
-rwxrwxr-x    1 1000     1000         279 Jan 10 10:00 run-warrior3
drwxrwxr-x    6 1000     1000        4.0K Jan 10 10:06 seesaw
-rw-rw-r--    1 1000     1000        1.3K Jan 10 10:00 setup.py
drwxrwxr-x    2 1000     1000        4.0K Jan 10 10:00 tests

/mnt/seesaw-kit # pip install -r requirements.txt 
Collecting Tornado<4.99999.99999,>=4.0
  Downloading tornado-4.5.3.tar.gz (484 kB)
     |████████████████████████████████| 484 kB 2.0 MB/s            
  Preparing metadata (setup.py) ... done
Collecting sockjs-tornado
  Downloading sockjs-tornado-1.0.7.tar.gz (21 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: Tornado, sockjs-tornado
  Building wheel for Tornado (setup.py) ... done
  Created wheel for Tornado: filename=tornado-4.5.3-cp310-cp310-linux_x86_64.whl size=420786 sha256=7802a90fb4d5606be8a589909e9953ba5554794c729fbc647b7a304357c65793
  Stored in directory: /root/.cache/pip/wheels/7a/fc/0f/8294151792cdc6cd7041df1467dbb536b4cff20d161d58501c
  Building wheel for sockjs-tornado (setup.py) ... done
  Created wheel for sockjs-tornado: filename=sockjs_tornado-1.0.7-py3-none-any.whl size=31709 sha256=3c6cad4f59103ff5d6979fdea1dba652dda08dccf39ef08a30232cc3b82bd6d9
  Stored in directory: /root/.cache/pip/wheels/e9/dd/6c/8645515dd3622f1a375f9d8b7c2387f20d006d62001d7bf0ce
Successfully built Tornado sockjs-tornado
Installing collected packages: Tornado, sockjs-tornado
Successfully installed Tornado-4.5.3 sockjs-tornado-1.0.7
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

# Just running run-pipeline3
/mnt/seesaw-kit # ./run-pipeline3 --help
Traceback (most recent call last):
  File "/mnt/seesaw-kit/./run-pipeline3", line 4, in <module>
    from seesaw.script.run_pipeline import main
  File "/mnt/seesaw-kit/seesaw/script/run_pipeline.py", line 11, in <module>
    from seesaw.runner import SimpleRunner
  File "/mnt/seesaw-kit/seesaw/runner.py", line 11, in <module>
    from seesaw.item import Item
  File "/mnt/seesaw-kit/seesaw/item.py", line 13, in <module>
    class ItemData(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'

# Running example pipeline (obv. fails same error)
/mnt/seesaw-kit # ./run-pipeline3 examples/example-pipeline.py example
Traceback (most recent call last):
  File "/mnt/seesaw-kit/./run-pipeline3", line 4, in <module>
    from seesaw.script.run_pipeline import main
  File "/mnt/seesaw-kit/seesaw/script/run_pipeline.py", line 11, in <module>
    from seesaw.runner import SimpleRunner
  File "/mnt/seesaw-kit/seesaw/runner.py", line 11, in <module>
    from seesaw.item import Item
  File "/mnt/seesaw-kit/seesaw/item.py", line 13, in <module>
    class ItemData(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
```

I am open to digging deeper into the code and figuring out a solution, maybe I can be of support. :)

### PR DESCRIPTION
**Pull request by Rexogamer**
Should fix #127, although the CI situation still needs sorting out (possibly switch to GH Actions?)

Tested - works on 3.8

### CODE REVIEW

**Comment by JustAnotherArchivist** [comment]
Thanks for working on this. I applaud anyone that stabs another knife in Python 2's back. It deserves it at this point. :-)

Haven't reviewed closely, but just some thoughts at a glance.

I think we should keep `run-pipeline3` and `run-warrior3` for compatibility. Lots of instructions and automation use them, for example all the (recent) `*-grab` repos and the Docker images.
But I think both those and the non-`3` versions should use `entry_points` rather than this 'scripts in the repo root' mess, which had some value with Python 2 compatibility (although not *really*) but is useless now.

I'd love to see `seesaw.six` go entirely. I hate vendored dependencies in general, but it's also unnecessary with Python 3. That's a larger refactoring though...

I'll look into CI migration.

**Comment by MPM1107** [comment]
I haven't tested to confirm, but I think the version of Tornado currently required by seesaw doesn't support python 3.10 either, so that could potentially need some work as well. Could someone double check that?

**Comment by JustAnotherArchivist** [comment]
Yeah, seesaw requires Tornado 4.x currently, which doesn't even officially support Python 3.7, so that wouldn't surprise me at all.

**Comment by Rexogamer** [comment]
I'd be willing to upgrade Tornado, but this would also break support for 3.4 and 3.5 (although considering the fact that even 3.6 is EOL this probably isn't that big of a deal, except for any remaining XP users which I highly doubt would still be able to use the Warrior)

**Comment by Rexogamer** [comment]
Testing locally, the Warrior loads and a task seems to be queued but there doesn't appear to be any progress? Not entirely sure what's going on

**Comment by JustAnotherArchivist** [comment]
Are you testing against prod?

**Comment by Rexogamer** [comment]
I was running the pipeline - I slightly suspect this is related to some of the code removed due to the Torando update, but hmm

**Comment by JustAnotherArchivist** [comment]
Please do not run any modified code against the live system.

**Comment by Rexogamer** [comment]
I was running the test pipeline - I was under the assumption this was test only and didn't send any data to the prod server, as it seemingly takes a localhost URL

**Comment by JustAnotherArchivist** [comment]
The ones in <https://github.com/ArchiveTeam/seesaw-kit/tree/development/tests>? Yeah, I think those are fine I think.

**Comment by Rexogamer** [comment]
It was the one listed in the README - so I think it's the test pipeline, yes

**Comment by TheTechRobo** [comment]
Is this compatible with existing seesaw scripts?

**Comment by Rexogamer** [comment]
> Is this compatible with existing seesaw scripts?

In terms of the entry points, yes - however, if any of them use Python < 3.5 they may need to be upgraded/modified

**Comment by Rexogamer** [comment]
Not sure if I have the bandwidth/ability to continue working on this, but I think it'd be best to split this PR in two (drop 2/cleanup, then see about fixing 3.10+)

**Comment by Rexogamer** [comment]
closing per above, apologies
